"""add manager regions

Revision ID: 294b33c5fff8
Revises: 20260602_0009
Create Date: 2026-06-03 00:07:07.413634
"""

from alembic import op
import sqlalchemy as sa



revision = '294b33c5fff8'
down_revision = '20260602_0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'city', name='uq_manager_city')
    )
    op.create_index(op.f('ix_manager_regions_id'), 'manager_regions', ['id'], unique=False)
    op.create_index(op.f('ix_manager_regions_manager_id'), 'manager_regions', ['manager_id'], unique=False)
    # op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    # op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # op.drop_index(op.f('email'), table_name='users')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # op.create_index(op.f('email'), 'users', ['email'], unique=True)
    # op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    # op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_manager_regions_manager_id'), table_name='manager_regions')
    op.drop_index(op.f('ix_manager_regions_id'), table_name='manager_regions')
    op.drop_table('manager_regions')
    # ### end Alembic commands ###
